scraper:
  start_urls:
    - https://www.ema.europa.eu/en/human-regulatory-overview/research-development
    - https://www.ema.europa.eu/en/human-regulatory-overview/marketing-authorisation
    - https://www.ema.europa.eu/en/human-regulatory-overview/post-authorisation

  
  allowed_domains:
    - ema.europa.eu
  
  file_patterns:
    - '\.pdf$'
    - '\.xlsx?$'
    - '\.docx?$'

  image_patterns:
    - '\.jpeg$'
    - '\.jpg$'
    - '\.png$'
    - '\.tiff$'

  video_patterns:
    - '\.mov$'

  audion_patterns:
    - '\.mp4$'

  exclude_patterns:
    - '_(?!en)[a-z]{2}\.pdf$'   # Non-English PDFs
    - '\.(svg|png|jpe?g|gif)$'  # Images
    - '^mailto:'
    - '^tel:'
  
  max_nodes: 100
  download_delay: 1

storage:
  engine: "mongo"
  database_path: ./data/crawl.db
  documents_path: ./data/documents

graph:
  path: ./data/graph.gpickle