name: scrapy
channels:
  - conda-forge
  - defaults
dependencies:
  - scrapy
  - pathlib
  - regex
  - playwright
  - pytest-playwright
  - yaml
  - pyyaml
  - pymongo
  - numpy
  - scikit-learn
  - scipy
  - openpyxl
  - pandas
  - markdownify
  - pandoc
  - html-to-markdown
  - pypandoc
  - tqdm
prefix: /home/moritz/miniconda3/envs/scrapy
